# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/76296/Desktop/ddr4_ex/ddr4_ex.srcs/sources_1/ip/axi_bram/axi_bram.xci
# IP: The module: 'axi_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/76296/Desktop/ddr4_ex/ddr4_ex.srcs/sources_1/ip/axi_bram/axi_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/76296/Desktop/ddr4_ex/ddr4_ex.srcs/sources_1/ip/axi_bram/axi_bram.xci
# IP: The module: 'axi_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/76296/Desktop/ddr4_ex/ddr4_ex.srcs/sources_1/ip/axi_bram/axi_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
