# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.srcs/sources_1/ip/Dmemery/Dmemery.xci
# IP: The module: 'Dmemery' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.srcs/sources_1/ip/Dmemery/Dmemery_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dmemery'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.srcs/sources_1/ip/Dmemery/Dmemery.xci
# IP: The module: 'Dmemery' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.srcs/sources_1/ip/Dmemery/Dmemery_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dmemery'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
