# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Code/Vivado/CGRA_On_RISCV/src/ALU.v
  C:/Code/Vivado/CGRA_On_RISCV/src/ALU_Control.v
  C:/Code/Vivado/CGRA_On_RISCV/src/Adder.v
  C:/Code/Vivado/CGRA_On_RISCV/src/DataMemory.v
  C:/Code/Vivado/CGRA_On_RISCV/src/ForwardingMUX.v
  C:/Code/Vivado/CGRA_On_RISCV/src/ForwardingUnit.v
  C:/Code/Vivado/CGRA_On_RISCV/src/HazardDetect.v
  C:/Code/Vivado/CGRA_On_RISCV/src/ID_EX.v
  C:/Code/Vivado/CGRA_On_RISCV/src/IF_ID.v
  C:/Code/Vivado/CGRA_On_RISCV/src/Instruction_Memory.v
  C:/Code/Vivado/CGRA_On_RISCV/src/MEM_WB.v
  C:/Code/Vivado/CGRA_On_RISCV/src/MUX32.v
  C:/Code/Vivado/CGRA_On_RISCV/src/MUX_Control.v
  C:/Code/Vivado/CGRA_On_RISCV/src/PC.v
  C:/Code/Vivado/CGRA_On_RISCV/src/Registers.v
  C:/Code/Vivado/CGRA_On_RISCV/src/Sign_Extend.v
  C:/Code/Vivado/CGRA_On_RISCV/src/VALU.v
  C:/Code/Vivado/CGRA_On_RISCV/src/VALU_ctrl.v
  C:/Code/Vivado/CGRA_On_RISCV/src/VControl.v
  C:/Code/Vivado/CGRA_On_RISCV/src/VEX_MEM.v
  C:/Code/Vivado/CGRA_On_RISCV/src/shift2.v
  C:/Code/Vivado/CGRA_On_RISCV/src/Control.v
  C:/Code/Vivado/CGRA_On_RISCV/src/EX_MEM.v
  C:/Code/Vivado/CGRA_On_RISCV/src/CPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.srcs/constrs_1/new/Frequency.xdc
set_property used_in_implementation false [get_files C:/Code/Vivado/CGRA_On_RISCV/src/project_1/project_1.srcs/constrs_1/new/Frequency.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
